### ISSUE TITLE
DDD factory methods vs. CQRS handlers

### ISSUE THREAD

**Issue by webdevilopers** [yvoyer/calculation-example#2]
Actually @yvoyer I don't understand this part enough yet.

In my example:
https://gist.github.com/yvoyer/a778ac744ddf10012864#file-dormercalculation-php
you suggested to use a factory method to add my a price - see lines 44 to 47.

ATM I have a similar scenario. A `Customer` ( <=> `DormerCalculation`) has an `Order` ( <=> `DormerCalculationPrice`).

In my first attempt the Handler created the `Order`. The constructor of the `Order` required the `Customer`.

After a while I thought about your example and read the "Factory method on aggregate root" chapter in the red book. In the example a `Forum` adds a `Post` / `Discussion` via factory method.
The advantage is too check if the forum wasn't already closed.

My problem is not so much deciding on which technique to choose. It's more about the terminology.

AFAIU "factory methods" are a Domain-Driven Design approach.
But using commands and handlers originally come from the CQRS approach.

Now does the CQRS appraoch recommend to move away the "factory methods" from the Domain Model and put the logic into the Handler - the way I tried in my first attempt?

Curious about your answer!

**Comment by webdevilopers** [comment]
Most of my Domain Models now have their own repository. Each repository has their `nextIdentity` method. Mostly returning a UUID. Using this method to create "aggregates" I think makes it impossible to use "factory methods" the way you suggested or?

Instead my `CalculateDormerHandler` would create new instances of `DormerCalculationPrice`\- including their UUID - add them to a `$prices` array and then pass it with everything else to the `DormerCalculation` constructor.

But this would require setting the UUID of the `dormerCalculation` on each `DormerCalculationPrice` already inside the handler.

**Comment by yvoyer** [comment]
First of all, the factory pattern is not something introduced by DDD. It a way of defining the right API for each operation.

Secondly, about your `Customer` -> `Order` case:
- I would suggest that you think as a DomainExpert to find out the right method name for the order creation. Instead of defining it using the CRUD way (Add or Create, Find, Update or Set and Delete), think about how the user would see this operation of creating an order. ie. `$customer->order(Items $itemsList): Order`. The `order()` method would be the factory method, and the handler would not know about the `Order` instance or how to build it.

``` php
// handler 

public function handle(Command $command) 
{
    if (! $command instanceof PlaceOrder) {
        // throw exception
    }
    $orderId = $this->identityGenerator->generateOrderId();

     $customer = $this->customer_repository->findActiveCustomer($command->customerId());
     $order = $customer->placeOrder($orderId, $command->products());

    $this->order_repository->saveOrder($order);

    $this->eventPublisher->publishAggregateEvent($customer->uncommitedEvents());
}

// Customer
public function placeOrder(OrderId $orderId, ProductCollection $products) 
{
    if ($this->hasActiveOrder()) {
        // Exception or update this order?
    }

    $order = Order::withProducts($orderId, $products);
    $this->setActiveOrder($order); // Private method

    // do other stuff like events ?
    return $order;
}
```

**Comment by yvoyer** [comment]
> Most of my Domain Models now have their own repository

Personnaly I don't define a repository for each entity, but a repository for each Aggregate root.

In your context, I would define a `CustomerRepository` that encapsulate either the generation of uuid or create an object responsible of generating UUID for the `CustomerAggregate`.

``` php
interface CustomerIdentityGenerator 
{
    /**
     * @return CustomerId
     */
    public function customerId();

    /**
     * @return OrderId
     */
    public function orderId();
}
```

That way the handler can rely on this class to give the identity to the aggregate root.

> But this would require setting the UUID of the dormerCalculation on each DormerCalculationPrice already inside the handler.

Does your `DormerCalculation` can change over time? I'm wondering if its really meant to be an `Entity`, maybe it could be a `ValueObject`? Could you provide a code sample or test to see the usage and better understand the problem. I'm finding it hard to suggest to you good refactoring when I can't see the big picture.

**Comment by webdevilopers** [comment]
Thanks @yvoyer ! I really misunderstood the role of the Handler here. It should just prepare the data (e.g. the `Id`s) for the factory method.

From a domain expert view, regarding the ubiquitous language, `placeOrder` indeed is the correct term.
The Offer then gets a `OrderStatus::STATUS_PENDING`.

In a next step an `OrderConfirmation` is sent by the `Customer`. Then the `Order` gets an UPDATE on the Status and done.

Currently I have a `ConfirmOrderHandler`. (BTW would you call it `CustomerConfirmOrderHandler`?)
This Handler updates the Status.

But looking at our `placeOrder` example I guess it is better to create a `confirmOrder` factory method on the `Customer`. Then the customer has to look up the `$orders` collection an update the Status, right?

```
class Customer()
{
    public function confirmOrder($orderId, OrderStatus $status)
    {
        $order = $this->orders[$orderId];
        $order->confirm($status);
    }
}

```

Actually the `OrderStatus` isn't even neccessary to be passed by the Handler. `Order` and its `confirm` method should know that it should set `OrderStatus::STATUS_CONFIRMED`.

Better?

**Comment by yvoyer** [comment]
> BTW would you call it CustomerConfirmOrderHandler?

No. Usually what I do is name my handler the same as the `Command`.

Personnally I would use `PlaceOrderCommand` as the command and `PlaceOrderHandler` as the handler.

> In a next step an OrderConfirmation is sent by the Customer. Then the Order gets an UPDATE on the Status and done.

From what I read on this sentence, the customer is the AggregateRoot, and I would implement something like this.

``` php
// Customer
public function placeOrder(/*whatever is needed to place order*/) {
   ...
  return $order;
}
public function confirmOrder(OrderId $id) {
    $order = $this->getOrder($orderId); // private that throw exception when not found
    $order->confirm(); // implement the Status pattern to make sure transitions are respected.
}

// Order
public function confirm() {
    $this->state->confirm(); // StatePattern
    or 
    // check that transitions are ok
    if ($this->isConfirmed() || $this->isShipped()) {
        throw TransitionException::InvalidTransition($this->state, self::CONFIRMED);
    }
    $this->state = self::CONFIRMED;
}
```

**Comment by webdevilopers** [comment]
Totally agree with this code! My `OrderStatus` is a Value Object BTW. So I place the constants there to get them via `OrderStatus::CONFIRMED`.

BTW: Why did you use `Order::withProducts` insted of `Order::place`. Because there maybe are multiple ways to init an `Order`?

**Comment by yvoyer** [comment]
About the state, you can find an [example](https://github.com/yvoyer/challenge-state/blob/feature/specifications/lib/Door/DoorState.php) of the state pattern I used for fun.

> BTW: Why did you use Order::withProducts insted of Order::place

The `withProduct` method is a factory method that creates order. Since I did not know what your code looked like. But the `Order::place()` seems weird. Your ubiquous language seems to tell that a customer place an order, and not the order. So it only seems logical to make a `Customer->placeOrder ()` at the instance level, not at the class level (static).

But since there maybe are multiple ways to build an order, these methods should be static to the `Order` class, since an order should always be instantiated with a valid state. 

Hope it helps to clarify?

**Comment by webdevilopers** [comment]
What really interests me is defining the actual aggregate root from the Order POV.

In my current company I have to processes:
- Customer talks to Employee. Employee logs in, creates an offer, sends it to Customer
- Customer receives Offer, agrees, informs Employee
- Employee logs in, enters the final order. Generates an Order Confirmation and sends it to the Customer
- Customer confirms order
- Employee logs in - an actual "Contract" is created. Work can begin.

Regarding the Offer and Order it is the Employee with the active part. In the red book there is this example "Table 1.5 Analyzing the best model for the business.":
http://www.informit.com/articles/article.aspx?p=1944876&seqNum=3

Now I started thinking that it should be something like:
- Employee->sendOfferToCustomer
- Employee->sendOrderToCustomer
- Customer->confirmOffer

or at least:
- Customer->receiveOffer
- Customer->receiveOrder
- Customer->confirmOffer

instead of:
- Customer->requestOffer
- Customer->placeOrder
- Customer->confirmOffer

This really confused me! ;) My feeling as a developer tells me to use the last approach.
What do you think @yvoyer ?

**Comment by webdevilopers** [comment]
Closed in favor of https://github.com/webdevilopers/php-ddd/issues/1
