### ISSUE TITLE
Move general DDD question so separate repository

### ISSUE THREAD

**Issue by webdevilopers** [yvoyer/calculation-example#3]
Though there is a great DDD Google group:
https://groups.google.com/forum/#!forum/dddcqrs

I would like to add some tutorials to my blog later:
http://blog.webdevilopers.net/category/php/ddd/

Until then I would like to start some general discussion about DDD with Symfony and Doctrine and put it here:
https://github.com/webdevilopers/php-ddd/blob/master/README.md

Is there any way to move issues between repos on github @yvoyer ?

**Comment by yvoyer** [comment]
@webdevilopers I could transfer ownership of the git repos to you, otherwise, I don't know of a way to transfer issues.

**Comment by webdevilopers** [comment]
Well it's only _2_ issues so far. I could do it manually later still. Just want to know if you want to join the new repo! ;)
